// react-test/src/common/tag.js
import styles from './tag.module.css';

const tagList = [
    { title: '\n                文学\n            ',
    tag_list: [ '小说', '随笔', '日本文学', '散文', '诗歌', '童话', '名著', '港台', '更多»' ] },
  { title: '\n                流行\n            ',
    tag_list: [ '漫画', '推理', '绘本', '青春', '科幻', '言情', '奇幻', '武侠', '更多»' ] },
  { title: '\n                文化\n            ',
    tag_list: [ '历史', '哲学', '传记', '设计', '建筑', '电影', '回忆录', '音乐', '更多»' ] },
  { title: '\n                生活\n            ',
    tag_list: [ '旅行', '励志', '教育', '职场', '美食', '灵修', '健康', '家居', '更多»' ] },
  { title: '\n                经管\n            ',
    tag_list: [ '经济学', '管理', '商业', '金融', '营销', '理财', '股票', '企业史', '更多»' ] },
  { title: '\n                科技\n            ',
    tag_list: [ '科普', '互联网', '编程', '交互设计', '算法', '通信', '神经网络', '更多»' ] }
];
const tagGroup = tagList.map((item) =>
    <div>
        <div>{item.title}</div>
        <div>{item.tag_list.map((tag)=><div>{tag}</div>)}</div>
    </div>);        
    
export const Tag = ()=>
    <div className={styles.tag}>
        {tagGroup}
    </div>

// douban-vue/src/components/tag.vue
<template>
    <div>
        <SectionNav title="热门标签">
            <span class="link-more">
                <a class="" href="/tag/?view=type&amp;icn=index-sorttags-all">所有热门标签»</a>
              </span>
        </SectionNav>
    <ul class="hot-tags-col5 s" data-dstat-areaid="54" data-dstat-mode="click,expose">
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    文学
                </li>
                <li>
                    <a href="/tag/小说" class="tag">小说</a>
                </li>
                <li>
                    <a href="/tag/随笔" class="tag">随笔</a>
                </li>
                <li>
                    <a href="/tag/日本文学" class="tag">日本文学</a>
                </li>
                <li class="last">
                      <a href="/tag/散文" class="tag">散文</a>
                </li>
                <li>
                    <a href="/tag/诗歌" class="tag">诗歌</a>
                </li>
                <li>
                    <a href="/tag/童话" class="tag">童话</a>
                </li>
                <li>
                    <a href="/tag/名著" class="tag">名著</a>
                </li>
                <li class="last">
                      <a href="/tag/港台" class="tag">港台</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#文学" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    流行
                </li>
                <li>
                    <a href="/tag/漫画" class="tag">漫画</a>
                </li>
                <li>
                    <a href="/tag/推理" class="tag">推理</a>
                </li>
                <li>
                    <a href="/tag/绘本" class="tag">绘本</a>
                </li>
                <li class="last">
                      <a href="/tag/青春" class="tag">青春</a>
                </li>
                <li>
                    <a href="/tag/科幻" class="tag">科幻</a>
                </li>
                <li>
                    <a href="/tag/言情" class="tag">言情</a>
                </li>
                <li>
                    <a href="/tag/奇幻" class="tag">奇幻</a>
                </li>
                <li class="last">
                      <a href="/tag/武侠" class="tag">武侠</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#流行" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    文化
                </li>
                <li>
                    <a href="/tag/历史" class="tag">历史</a>
                </li>
                <li>
                    <a href="/tag/哲学" class="tag">哲学</a>
                </li>
                <li>
                    <a href="/tag/传记" class="tag">传记</a>
                </li>
                <li class="last">
                      <a href="/tag/设计" class="tag">设计</a>
                </li>
                <li>
                    <a href="/tag/建筑" class="tag">建筑</a>
                </li>
                <li>
                    <a href="/tag/电影" class="tag">电影</a>
                </li>
                <li>
                    <a href="/tag/回忆录" class="tag">回忆录</a>
                </li>
                <li class="last">
                      <a href="/tag/音乐" class="tag">音乐</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#文化" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    生活
                </li>
                <li>
                    <a href="/tag/旅行" class="tag">旅行</a>
                </li>
                <li>
                    <a href="/tag/励志" class="tag">励志</a>
                </li>
                <li>
                    <a href="/tag/教育" class="tag">教育</a>
                </li>
                <li class="last">
                      <a href="/tag/职场" class="tag">职场</a>
                </li>
                <li>
                    <a href="/tag/美食" class="tag">美食</a>
                </li>
                <li>
                    <a href="/tag/灵修" class="tag">灵修</a>
                </li>
                <li>
                    <a href="/tag/健康" class="tag">健康</a>
                </li>
                <li class="last">
                      <a href="/tag/家居" class="tag">家居</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#生活" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    经管
                </li>
                <li>
                    <a href="/tag/经济学" class="tag">经济学</a>
                </li>
                <li>
                    <a href="/tag/管理" class="tag">管理</a>
                </li>
                <li>
                    <a href="/tag/商业" class="tag">商业</a>
                </li>
                <li class="last">
                      <a href="/tag/金融" class="tag">金融</a>
                </li>
                <li>
                    <a href="/tag/营销" class="tag">营销</a>
                </li>
                <li>
                    <a href="/tag/理财" class="tag">理财</a>
                </li>
                <li>
                    <a href="/tag/股票" class="tag">股票</a>
                </li>
                <li class="last">
                      <a href="/tag/企业史" class="tag">企业史</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#经管" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    科技
                </li>
                <li>
                    <a href="/tag/科普" class="tag">科普</a>
                </li>
                <li>
                    <a href="/tag/互联网" class="tag">互联网</a>
                </li>
                <li>
                    <a href="/tag/编程" class="tag">编程</a>
                </li>
                <li class="last">
                      <a href="/tag/交互设计" class="tag">交互设计</a>
                </li>
                <li>
                    <a href="/tag/算法" class="tag">算法</a>
                </li>
                <li>
                    <a href="/tag/通信" class="tag">通信</a>
                </li>
                <li>
                    <a href="/tag/神经网络" class="tag">神经网络</a>
                </li>
                <li class="last">
                      <a href="/tag/?view=type&amp;icn=index-sorttags-hot#科技" class="tag more_tag">更多»</a>
                </li>
            </ul>
        </li>
        </ul>
    </div>
</template>
<script>
    import SectionNav from './sectionNav.vue'
    export default{
        name:"Review",
        data(){
            return{
                items : [...Array(10).keys()],
                infos : ['下载豆瓣客户端', '登录/注册']
            }
        },
        components:{
            SectionNav,
        }
    }
    </script>

<style scoped>
.list-col5 {
    width: 100%;
    display: grid;
    grid-template-columns: repeat(5, 20%);
    grid-column-gap: 9px;

}

.img{
    width: 100px;  
    height: auto;
}
.more-meta{
        display: none;
}
.link-more{
        font-size: 13px;
        color: #3377aa;
        margin: 15px;
}
</style>
