// react-test/src/common/tag.js
import styles from './tag.module.css';

const tagList = [
    { title: '\n                文学\n            ',
    tag_list: [ '小说', '随笔', '日本文学', '散文', '诗歌', '童话', '名著', '港台', '更多»' ] },
  { title: '\n                流行\n            ',
    tag_list: [ '漫画', '推理', '绘本', '青春', '科幻', '言情', '奇幻', '武侠', '更多»' ] },
  { title: '\n                文化\n            ',
    tag_list: [ '历史', '哲学', '传记', '设计', '建筑', '电影', '回忆录', '音乐', '更多»' ] },
  { title: '\n                生活\n            ',
    tag_list: [ '旅行', '励志', '教育', '职场', '美食', '灵修', '健康', '家居', '更多»' ] },
  { title: '\n                经管\n            ',
    tag_list: [ '经济学', '管理', '商业', '金融', '营销', '理财', '股票', '企业史', '更多»' ] },
  { title: '\n                科技\n            ',
    tag_list: [ '科普', '互联网', '编程', '交互设计', '算法', '通信', '神经网络', '更多»' ] }
];
const tagGroup = tagList.map((item) =>
    <div>
        <div>{item.title}</div>
        <div>{item.tag_list.map((tag)=><div>{tag}</div>)}</div>
    </div>);        
    
export const Tag = ()=>
    <div className={styles.tag}>
        {tagGroup}
    </div>

// douban/src/mobile_components/tag.vue
<template>
    <div>
        <SectionNav title="热门标签">
            <span class="link-more">
                <a class="" href="/tag/?view=type&amp;icn=index-sorttags-all">所有热门标签»</a>
              </span>
        </SectionNav>
    <ul class="hot-tags-col5 s" data-dstat-areaid="54" data-dstat-mode="click,expose">
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    文学
                </li>
                <li>
                    <router-link  to="/tag/小说"  class="tag">小说</router-link>
                </li>
                <li>
                    <router-link to="/tag/随笔" class="tag">随笔</router-link>
                </li>
                <li>
                    <router-link to="/tag/日本文学" class="tag">日本文学</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/散文" class="tag">散文</router-link>
                </li>
                <li>
                    <router-link to="/tag/诗歌" class="tag">诗歌</router-link>
                </li>
                <li>
                    <router-link to="/tag/童话" class="tag">童话</router-link>
                </li>
                <li>
                    <router-link to="/tag/名著" class="tag">名著</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/港台" class="tag">港台</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#文学" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    流行
                </li>
                <li>
                    <router-link to="/tag/漫画" class="tag">漫画</router-link>
                </li>
                <li>
                    <router-link to="/tag/推理" class="tag">推理</router-link>
                </li>
                <li>
                    <router-link to="/tag/绘本" class="tag">绘本</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/青春" class="tag">青春</router-link>
                </li>
                <li>
                    <router-link to="/tag/科幻" class="tag">科幻</router-link>
                </li>
                <li>
                    <router-link to="/tag/言情" class="tag">言情</router-link>
                </li>
                <li>
                    <router-link to="/tag/奇幻" class="tag">奇幻</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/武侠" class="tag">武侠</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#流行" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    文化
                </li>
                <li>
                    <router-link to="/tag/历史" class="tag">历史</router-link>
                </li>
                <li>
                    <router-link to="/tag/哲学" class="tag">哲学</router-link>
                </li>
                <li>
                    <router-link to="/tag/传记" class="tag">传记</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/设计" class="tag">设计</router-link>
                </li>
                <li>
                    <router-link to="/tag/建筑" class="tag">建筑</router-link>
                </li>
                <li>
                    <router-link to="/tag/电影" class="tag">电影</router-link>
                </li>
                <li>
                    <router-link to="/tag/回忆录" class="tag">回忆录</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/音乐" class="tag">音乐</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#文化" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    生活
                </li>
                <li>
                    <router-link to="/tag/旅行" class="tag">旅行</router-link>
                </li>
                <li>
                    <router-link to="/tag/励志" class="tag">励志</router-link>
                </li>
                <li>
                    <router-link to="/tag/教育" class="tag">教育</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/职场" class="tag">职场</router-link>
                </li>
                <li>
                    <router-link to="/tag/美食" class="tag">美食</router-link>
                </li>
                <li>
                    <router-link to="/tag/灵修" class="tag">灵修</router-link>
                </li>
                <li>
                    <router-link to="/tag/健康" class="tag">健康</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/家居" class="tag">家居</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#生活" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    经管
                </li>
                <li>
                    <router-link to="/tag/经济学" class="tag">经济学</router-link>
                </li>
                <li>
                    <router-link to="/tag/管理" class="tag">管理</router-link>
                </li>
                <li>
                    <router-link to="/tag/商业" class="tag">商业</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/金融" class="tag">金融</router-link>
                </li>
                <li>
                    <router-link to="/tag/营销" class="tag">营销</router-link>
                </li>
                <li>
                    <router-link to="/tag/理财" class="tag">理财</router-link>
                </li>
                <li>
                    <router-link to="/tag/股票" class="tag">股票</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/企业史" class="tag">企业史</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#经管" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        <li>
            <ul class="clearfix">
                <li class="tag_title">
                    科技
                </li>
                <li>
                    <router-link to="/tag/科普" class="tag">科普</router-link>
                </li>
                <li>
                    <router-link to="/tag/互联网" class="tag">互联网</router-link>
                </li>
                <li>
                    <router-link to="/tag/编程" class="tag">编程</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/交互设计" class="tag">交互设计</router-link>
                </li>
                <li>
                    <router-link to="/tag/算法" class="tag">算法</router-link>
                </li>
                <li>
                    <router-link to="/tag/通信" class="tag">通信</router-link>
                </li>
                <li>
                    <router-link to="/tag/神经网络" class="tag">神经网络</router-link>
                </li>
                <li class="last">
                      <router-link to="/tag/?view=type&amp;icn=index-sorttags-hot#科技" class="tag more_tag">更多»</router-link>
                </li>
            </ul>
        </li>
        </ul>
    </div>
</template>
<script>
    import SectionNav from './sectionNav.vue'

    export default{
        name:"Tag",
        data(){
            return{
                items : [...Array(10).keys()],
            }
        },
        components:{
            SectionNav,
        }
    }
    </script>

<style scoped>
ul {
    width: 100%;
    display: flex;
    flex-wrap: wrap;
    border-bottom: 1px dashed #e5ebe4;
}
ul li .tag_title{
    flex-basis: 100%;
}
li .tag {
    display: inline-block;
    font-size: 13px;
    background-color: #f5f5f5;
    padding: 2px 11px 0;
    margin: 0 3px 5px 0;
    line-height: 20px;
}
li .tag:hover{
    background-color: #e8e8e8;
}

.img{
    width: 100px;  
    height: auto;
}
.more-meta{
    display: none;
}
.link-more{
    font-size: 13px;
    color: #3377aa;
    margin: 15px;
}
</style>
